CREATE DATABASE IF NOT EXISTS lab7;
USE lab7;

CREATE TABLE IF NOT EXISTS survey_responses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  submitted_at DATETIME NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  q1_lang VARCHAR(50) NOT NULL,
  q2_hours VARCHAR(20) NOT NULL,
  q3_ai VARCHAR(20) NOT NULL,
  q4_hard TEXT NOT NULL,
  q5_wish TEXT NULL,
  file_name VARCHAR(255) NULL,
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
